name: biomni
channels:
  - conda-forge
  - bioconda
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  # Force CPU-only variants to reduce image size and disk usage (avoid large CUDA libs)
  - cpuonly # from pytorch channel; micromamba/conda will map
  # Core numeric & utils
  - numpy=2.1
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - networkx
  - statsmodels
  - scikit-learn
  - pyyaml
  - requests
  - tqdm
  - regex
  - sympy
  - pyarrow
  # Bio / scientific
  - biopython
  - pybedtools
  - viennarna
  - msprime
  - cooler
  - pyliftover
  - pykalman
  - trackpy
  - scanpy
  - scvi-tools
  - simpleitk
  - nibabel
  - opencv
  - rdkit
  - gseapy
  - gget
  - reportlab
  - python-louvain
  - muscle
  # ML / imaging
  - pytorch
  - torchvision
  - torchaudio
  - accelerate
  # Jupyter / dev
  - jupyter
  - notebook
  - ipykernel
  - pytest
  # Optional chemistry / pharma (uncomment if needed)
  # - openbabel
  - pip:
      - langchain
      - langgraph==0.3.18
      - langchain-openai
      - langchain-anthropic
      - langchain-ollama
      - langchain-community
      - openai
      - transformers
      - sentencepiece
      - hypha-rpc==0.20.78
      - anyio==4.10.0
      - python-dotenv
      - mcp
      - tooluniverse
      - gradio
      - beautifulsoup4
      - lxml
      - PyPDF2
      - googlesearch-python
      - arxiv
      - harmonypy
      - cobra # moved to pip to avoid libSBML solve on osx-arm64
      - cellpose
      - fastremap
      - DeepPurpose
      - FlowCytometryTools
      - tdc
      - pymed
      # Optional / uncommon (leave commented unless required)
      # - eval-single-anndata
      # - torchmetrics
